### ISSUE TITLE
Can you add a score onto the pygame window along with tkinter?

### ISSUE THREAD

**Issue by NikQATech** [MikeJConner/snakeRemake#2]
Hello, can you please make a "Score" functionality? To be able to immediately see the Score, and not just after losing

**Comment by MikeJConner** [comment]
everything drawn on the screen is based on the assumption that the window is the size of the board and that the board fills the entire screen. We could add in a score counter but that would be quite a bit of effort to reorganize everything else

**Comment by MikeJConner** [comment]
I went and tacked a score onto the bottom, I think it would look nicer at the top personally but its much simpler to stick it down there
